# Generated by Django 5.1.3 on 2024-11-25 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('water', 'Agua'), ('food', 'Comida Balanceada')], max_length=50, unique=True)),
                ('current_quantity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='resources.resource')),
            ],
        ),
    ]
